### ISSUE TITLE
Crash When Placing SUNNY Card

### ISSUE THREAD

**Issue by HockeyZman2000** [MarbleGateKeeper/OmnipotentCard#1]
[crash-2021-12-12_16.37.36-client.txt](https://github.com/MarbleGateKeeper/OmnipotentCard/files/7700014/crash-2021-12-12_16.37.36-client.txt)

I was messing around with the mod and I placed the card down to turn the weather to sunny while it was already sunny. Don't know if that is what caused it but just thought I'd put the crash here.

**Comment by MarbleGateKeeper** [comment]
Well, it looks like Waila was trying to get block drop when block data syncing is incomplete. It is unexpected.
Thanks for your report! It'll get fixed soon.
**By the way Jade or WTHIT, which one did you use?**

**Comment by MarbleGateKeeper** [comment]
Well. [Beta 0.1.4](https://www.curseforge.com/minecraft/mc-mods/omnipotent-card/files/3564399) is uploaded, this problem is fixed.
